version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sensorhub
      POSTGRES_PASSWORD: shpass
      POSTGRES_DB: sensorhub
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: db@db.com
      PGADMIN_DEFAULT_PASSWORD: xxx
    ports:
      - 8080:80
    volumes:
      - ./.pgadmin-data:/root/.pgadmin
