dependencies:
  '@rush-temp/server': 'file:projects/server.tgz'
packages:
  'file:projects/server.tgz':
    dev: false
    name: '@rush-temp/server'
    resolution:
      integrity: sha512-AqJgfqH/fmrHvDrZmkINr9yLPV6ZfqQjkNa65HwcPJdJ9unJq0X4e8m676oOL0F2f00LXJKDtLkepF+SLqotAw==
      tarball: 'file:projects/server.tgz'
    version: 0.0.0
registry: 'https://registry.npmjs.org/'
shrinkwrapMinorVersion: 9
shrinkwrapVersion: 3
specifiers:
  '@rush-temp/server': 'file:./projects/server.tgz'
