dependencies:
  '@rush-temp/server': 'file:projects/server.tgz'
  sequelize: 5.21.3
packages:
  /@types/node/13.1.8:
    dev: false
    resolution:
      integrity: sha512-6XzyyNM9EKQW4HKuzbo/CkOIjn/evtCmsU+MUM1xDfJ+3/rNjBttM1NgN7AOQvN6tP1Sl1D1PIKMreTArnxM9A==
  /any-promise/1.3.0:
    dev: false
    resolution:
      integrity: sha1-q8av7tzqUugJzcA3au0845Y10X8=
  /bluebird/3.7.2:
    dev: false
    resolution:
      integrity: sha512-XpNj6GDQzdfW+r2Wnn7xiSAd7TM3jzkxGXBGTtWKuSXv1xUV+azxAm8jdWZN06QTQk+2N2XB9jRDkvbmQmcRtg==
  /cls-bluebird/2.1.0:
    dependencies:
      is-bluebird: 1.0.2
      shimmer: 1.2.1
    dev: false
    resolution:
      integrity: sha1-N+8eCAqP+1XC9BZPU28ZGeeWiu4=
  /debug/4.1.1:
    dependencies:
      ms: 2.1.2
    dev: false
    resolution:
      integrity: sha512-pYAIzeRo8J6KPEaJ0VWOh5Pzkbw/RetuzehGM7QRRX5he4fPHx2rdKMB256ehJCkX+XRQm16eZLqLNS8RSZXZw==
  /dottie/2.0.2:
    dev: false
    resolution:
      integrity: sha512-fmrwR04lsniq/uSr8yikThDTrM7epXHBAAjH9TbeH3rEA8tdCO7mRzB9hdmdGyJCxF8KERo9CITcm3kGuoyMhg==
  /inflection/1.12.0:
    dev: false
    engines:
      '0': node >= 0.4.0
    resolution:
      integrity: sha1-ogCTVlbW9fa8TcdQLhrstwMihBY=
  /is-bluebird/1.0.2:
    dev: false
    engines:
      node: '>=0.10.0'
    resolution:
      integrity: sha1-CWQ5Bg9KpBGr7hkUOoTWpVNG1uI=
  /lodash/4.17.15:
    dev: false
    resolution:
      integrity: sha512-8xOcRHvCjnocdS5cpwXQXVzmmh5e5+saE2QGoeQmbKmRS6J3VQppPOIt0MnmE+4xlZoumy0GPG0D0MVIQbNA1A==
  /moment-timezone/0.5.27:
    dependencies:
      moment: 2.24.0
    dev: false
    resolution:
      integrity: sha512-EIKQs7h5sAsjhPCqN6ggx6cEbs94GK050254TIJySD1bzoM5JTYDwAU1IoVOeTOL6Gm27kYJ51/uuvq1kIlrbw==
  /moment/2.24.0:
    dev: false
    resolution:
      integrity: sha512-bV7f+6l2QigeBBZSM/6yTNq4P2fNpSWj/0e7jQcy87A8e7o2nAfP/34/2ky5Vw4B9S446EtIhodAzkFCcR4dQg==
  /ms/2.1.2:
    dev: false
    resolution:
      integrity: sha512-sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==
  /retry-as-promised/3.2.0:
    dependencies:
      any-promise: 1.3.0
    dev: false
    resolution:
      integrity: sha512-CybGs60B7oYU/qSQ6kuaFmRd9sTZ6oXSc0toqePvV74Ac6/IFZSI1ReFQmtCN+uvW1Mtqdwpvt/LGOiCBAY2Mg==
  /semver/6.3.0:
    dev: false
    hasBin: true
    resolution:
      integrity: sha512-b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw==
  /sequelize-pool/2.3.0:
    dev: false
    engines:
      node: '>= 6.0.0'
    resolution:
      integrity: sha512-Ibz08vnXvkZ8LJTiUOxRcj1Ckdn7qafNZ2t59jYHMX1VIebTAOYefWdRYFt6z6+hy52WGthAHAoLc9hvk3onqA==
  /sequelize/5.21.3:
    dependencies:
      bluebird: 3.7.2
      cls-bluebird: 2.1.0
      debug: 4.1.1
      dottie: 2.0.2
      inflection: 1.12.0
      lodash: 4.17.15
      moment: 2.24.0
      moment-timezone: 0.5.27
      retry-as-promised: 3.2.0
      semver: 6.3.0
      sequelize-pool: 2.3.0
      toposort-class: 1.0.1
      uuid: 3.4.0
      validator: 10.11.0
      wkx: 0.4.8
    dev: false
    engines:
      node: '>=6.0.0'
    resolution:
      integrity: sha512-ptdeAxwTY0zbj7AK8m+SH3z52uHVrt/qmOTSIGo/kyfnSp3h5HeKlywkJf5GEk09kuRrPHfWARVSXH1W3IGU7g==
  /shimmer/1.2.1:
    dev: false
    resolution:
      integrity: sha512-sQTKC1Re/rM6XyFM6fIAGHRPVGvyXfgzIDvzoq608vM+jeyVD0Tu1E6Np0Kc2zAIFWIj963V2800iF/9LPieQw==
  /toposort-class/1.0.1:
    dev: false
    resolution:
      integrity: sha1-f/0feMi+KMO6Rc1OGj9e4ZO9mYg=
  /uuid/3.4.0:
    dev: false
    hasBin: true
    resolution:
      integrity: sha512-HjSDRw6gZE5JMggctHBcjVak08+KEVhSIiDzFnT9S9aegmp85S/bReBVTb4QTFaRNptJ9kuYaNhnbNEOkbKb/A==
  /validator/10.11.0:
    dev: false
    engines:
      node: '>= 0.10'
    resolution:
      integrity: sha512-X/p3UZerAIsbBfN/IwahhYaBbY68EN/UQBWHtsbXGT5bfrH/p4NQzUCG1kF/rtKaNpnJ7jAu6NGTdSNtyNIXMw==
  /wkx/0.4.8:
    dependencies:
      '@types/node': 13.1.8
    dev: false
    resolution:
      integrity: sha512-ikPXMM9IR/gy/LwiOSqWlSL3X/J5uk9EO2hHNRXS41eTLXaUFEVw9fn/593jW/tE5tedNg8YjT5HkCa4FqQZyQ==
  'file:projects/server.tgz':
    dependencies:
      sequelize: 5.21.3
    dev: false
    name: '@rush-temp/server'
    resolution:
      integrity: sha512-OiMN6pvjCi3GRRzEn/B3g3RPoNQO4WtONu5l8NPmTdnCrGvpuFRIT9R02p1NNj+IhNTDqOrqDwusTESN2EQJEw==
      tarball: 'file:projects/server.tgz'
    version: 0.0.0
registry: 'https://registry.npmjs.org/'
shrinkwrapMinorVersion: 9
shrinkwrapVersion: 3
specifiers:
  '@rush-temp/server': 'file:./projects/server.tgz'
  sequelize: ^5.21.3
